config/routes.rb
Rails.application.routes.draw do
  resources :items do
    member do
      put "like" => "items#upvote"
      put "unlike" => "items#downvote"
    end
  end
  resources :memberships
  devise_for :users
  root to: "items#index"
  get 'dashboard' => "pages#dashboard"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
      can :read, :all
      can :manage, Item do |item|
        item.try(:user) == user
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :price, presence: true
  belongs_to :user
  has_attached_file :image
  has_attached_file :resource

  validates_attachment_content_type :image,
  content_type:  /^image\/(png|gif|jpeg)/,
  message: "Only images allowed"

  validates_attachment_content_type :resource,
  content_type: ['application/pdf'],
  message: "Only pdfs allowed"

  validates :image, attachment_presence: true
  acts_as_votable
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  include AASM

  aasm column: 'state' do
  state :pending, initial: true
  state :processing
  state :finished
  state :errored

  event :process, after: :charge_card do
    transitions from: :pending, to: :processing
  end

  event :finish do
    transitions from: :processing, to: :finished
  end

  event :fail do
    transitions from: :processing, to: :errored
  end

  before_create :populate_quid

  def charge_card
   begin
    save!
    charge = Stripe::Charge.create(
      amount: self.amount,
      currency: "usd",
      card: self.stripe_token,
      description: "Book Sale"
      )
    self.update(stripe_id: charge.id)
    self.finish!
     rescue Stripe::StripeError => e
    self.update_attributes(error: e.message)
    self.fail!
    end
  end

  private

  def populate_quid
    self.quid = SecureRandom.uuid()
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, notice: "You are not authorized to access this area"
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  respond_to :html

  def index
    @items = Item.order(:cached_weighted_score => :desc)
    @items = Item.last(4)
  end

  def show
    respond_with(@item)
  end

  def new
    @item = Item.new
    respond_with(@item)
  end

  def edit
    authorize! :manage, @item
  end

  def create
    @item = current_user.items.new(item_params)
    @item.save
    respond_with(@item)
  end

  def update
    authorize! :manage, @item
    @item.update(item_params)
    respond_with(@item)
  end

  def upvote
    @item.upvote_from current_user, :vote_weight => 3
    redirect_to items_path
  end

  def downvote
    @item.downvote_from current_user
    redirect_to items_path
  end

  def destroy
    authorize! :manage, @item
    @item.destroy
    respond_with(@item)
  end

  private
    def set_item
      @item = Item.friendly.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :creator, :description, :price, :availability, :image, :resource)
    end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  def index
    @memberships = Membership.all
  end

  def new
    @membership = Membership.new
  end

  def create
    @membership = Membership.new
    if @membership.save(membership_params)
      redirect_to root_path
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @membership.update(membership_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @membership.destroy
      redirect_to membership_path
    end
  end

  private

  def set_membership
    @membership = Membership.find(params[:edit])
  end

  def membership_params
    params.require(:membership).permit(:member_email, :amount, :quid)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]

  def index
    if current_user
      redirect_to items_path
    end
    @items = Item.last(4)
  end

  def dashboard
    @items = current_user.items
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def create

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for(@item, html: {class: "form-item"}) do |f| %>
  <%= f.error_notification %>

    <%= f.input :name, required: true, autofocus: true, label: false, placeholder: "Name", input_html: {class: "form-control"} %>
    <%= f.input :creator, required: false, autofocus: true, label: false, placeholder: "Creator", input_html: {class: "form-control"} %>
    <%= f.input :description, required: false, autofocus: true, label: false, placeholder: "Description", input_html: {class: "form-control"} %>
    <%= f.input :price, required: true, autofocus: true, label: false, placeholder: "Price", input_html: {class: "form-control"} %>
    <%= f.input :image %>

    <div class="checkbox text-center">
    <p>Availability</p>
    <%= f.input :availability, required: false, label: false %>
    </div>
    <%= f.button :submit, "Submit", class: "btn btn-primary btn-block" %>
<% end %>

app/views/items/_header.html.erb
<div class="row">
  <%= render @items %>
</div>

app/views/items/_item.html.erb
<div class="col-md-3">
  <div class="thumbnail">
    <%= link_to item_path(item) do %>
    <%= image_tag item.image.url(:original), class: "img-responsive" %>
    <% end %>
    <div class="caption">
      <h5><%= link_to item.name, item_path(item) %></h5>
      <p>$<%= item.price %></p>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<h1 class="text-center">Edit item</h1>

<%= render 'form' %>

<h4 class="text-center"><%= link_to 'Show', @item %></h4>
<h4 class="text-center"><%= link_to 'Back', items_path %></h4>

app/views/items/index.html.erb
<% @items.each do |item| %>
  <div class="col-sm-3 col-md-3">
    <div class="thumbnail thumb-box">
    <h4 style="text-align:center;"><%= link_to item.name, item %></h4>
      <%= link_to image_tag( item.image, size: "250x300" ), item %>
      <div class="caption" style="text-align:center;">
        <%= link_to like_item_path(item),  class: "like", method: :put do %>
           <button type="button" class="btn btn-info" aria-label="Left Align">
             <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
             <span class="badge"><%= item.get_upvotes.size %></span>
           </button>
        <% end %>
        <%= link_to unlike_item_path(item), class: "like", method: :put do %>
          <button type="button" class="btn btn-info" aria-label="Left Align">
           <span class="glyphicon glyphicon-thumbs-down glyphicon-align-center" aria-hidden="true"></span>
           <span class="badge"><%= item.get_downvotes.size %></span>
          </button>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/items/new.html.erb
<h1 class="text-center">New item</h1>

<%= render 'form' %>

<h4 class="text-center"><%= link_to 'Items', items_path %></h4>

app/views/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5">
      <%= image_tag @item.image.url(:original), class: "img-responsive" %>
    </div>
    <div class="col-md-7">
      <div class="col-md-6">
        <h3><%= @item.name %> <%= @item.creator %></h3>
        <p class="justify"><%= @item.description %></p>
        <h4 class="text-left">$<%= @item.price %></h4>
        <%= link_to "Edit", edit_item_path(@item)  %>
        <%= link_to "Back", item_path  %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "RemembrIt", root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li><%= link_to "Dashboard", dashboard_path %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RemembrIt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</head>
<body>
<%= render "layouts/header" %>
<div class="container">
  <% flash.each do |type, message| %>
  <div class="alert alert-info fade-in">
    <button class="close" data-dismiss="alert">x</button>
    <%= message %>
  </div>
  <% end %>
<%= yield %>
</div>
</body>
</html>

app/views/memberships/_form.html.erb
<%= simple_form_for(@membership, html: {class: "member-item"}) do |f| %>
  <%= f.error_notification %>

    <%= f.input :member_email, required: true, autofocus: true, label: false, placeholder: "email", input_html: {class: "form-control"} %>
    <%= f.input :amount, required: true, autofocus: true, label: false, placeholder: "Amount", input_html: {class: "form-control"} %>
    <%= f.button :submit, "Submit", class: "btn btn-primary btn-block" %>
<% end %>

app/views/memberships/index.html.erb
<% @memberships.each do |membership| %>
  <%= membership.member_email %>
<% end %>

app/views/memberships/new.html.erb
<h3 class="text-center">Register</h3>

<%= render "form" %>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="row">
  <h1 class="text-center">Main Control</h1>
    <div class="col-md-4">
      <h3 class="text-center">
        Items <%= link_to "New Item", new_item_path, class: "btn btn-primary bt-sm"  %>
      </h3>
      <table class="table table-condensed">
          <thead>
            <tr>
              <th>Id</th>
              <th>Name</th>
              <th>Available</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><%= link_to item.name, item_path(item) %></td>
              <td><%= item.availability %></td>
              <td><%= link_to "Edit", edit_item_path(item) %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
    </div>
    <div class="col-md-4">
      <h3 class="text-center">
        Votes
      </h3>
    </div>
    <div class="col-md-4">
      <h3 class="text-center">
        Sales
      </h3>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="col-md-6">
  <h4>Hello</h4>
</div>